"""
Second-reader (第2リーダー) double-reading support.

Workflow context
----------------
1. The first grader (施設側) analyzes a folder, presses Export → CSV files are
   written to ``{output_dir}`` and the MedSAM metadata bundle is written to
   ``{output_dir}/export/images|masks|meta/{institution_id}/…``.
2. The second reader logs in with role 第2リーダー, selects the parent folder of
   the metadata folder (the first grader's output folder — or the ``export``/
   ``meta`` folder itself; all are normalized here), and the app automatically
   scans it for the exported en-face images.
3. After the second reader grades and presses Export, the 統合解析データ button
   merges both CSVs with the reading-center RPD(20%) adoption rule
   (``tools/reading_center_rpd/compute_adopted_from_dual_csv.py``).
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

ROLE_FIRST_GRADER = "GRADER1"
ROLE_SECOND_READER = "READER2"
READER_ROLE_KEY = "reader_role"

READER_ROLE_OPTIONS = [
    (ROLE_FIRST_GRADER, "第1グレーダー（施設読影）"),
    (ROLE_SECOND_READER, "第2リーダー（セカンドリーディング）"),
]

# Session keys used across dashboard / results screens
SR_SCAN_ROOT_KEY = "second_reader_scan_root"
SR_FIRST_GRADER_CSV_KEY = "second_reader_first_grader_csv"
SR_CSV_PATH_KEY = "second_reader_csv_path"

_IMAGE_PATTERNS = ("*.png", "*.tif", "*.tiff", "*.jpg", "*.jpeg")

# CSVs generated by the merge step (never candidates for the first-grader CSV)
_MERGED_CSV_MARKERS = ("adopted_values", "recheck_list", "integrated")
_SECOND_READER_DIR_PREFIX = "second_reader_output"
_INTEGRATED_DIR_PREFIX = "integrated_output"
# Sibling folders produced by this workflow — never scanned for exports/CSVs
_WORKFLOW_OUTPUT_PREFIXES = (_SECOND_READER_DIR_PREFIX, _INTEGRATED_DIR_PREFIX)


def _is_workflow_output_dir(d: Path) -> bool:
    return d.name.startswith(_WORKFLOW_OUTPUT_PREFIXES)


def get_reader_role(session: Any) -> str:
    """Return the logged-in reader role (defaults to first grader)."""
    try:
        role = session.get(READER_ROLE_KEY)
    except Exception:
        role = None
    return str(role or ROLE_FIRST_GRADER).strip().upper()


def is_second_reader(session: Any) -> bool:
    return get_reader_role(session) == ROLE_SECOND_READER


@dataclass
class SecondReaderScan:
    """Result of scanning the metadata parent folder for second reading."""

    selected: Path
    export_dir: Path
    scan_root: Path            # parent of export/ — where the first grader CSVs live
    images_dir: Path           # folder whose images are queued for grading
    images: List[Path] = field(default_factory=list)
    meta_files: List[Path] = field(default_factory=list)
    first_grader_csvs: List[Path] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


def _dir_is_export_bundle(d: Path) -> bool:
    try:
        return d.is_dir() and (d / "images").is_dir() and (d / "meta").is_dir()
    except OSError:
        return False


def _candidate_export_dirs(selected: Path) -> Iterable[Path]:
    """Places to look for the ``export/images|masks|meta`` bundle."""
    yield selected
    yield selected / "export"
    # user selected meta/ or meta/{INSTITUTION}/ or images/…
    yield selected.parent
    yield selected.parent.parent
    # user selected the folder that CONTAINS the output folder(s)
    try:
        children = sorted(
            (
                c
                for c in selected.iterdir()
                if c.is_dir() and not _is_workflow_output_dir(c)
            ),
            key=lambda c: c.stat().st_mtime,
            reverse=True,
        )
    except OSError:
        children = []
    for child in children[:40]:
        yield child / "export"
        yield child


def _glob_images(directory: Path) -> List[Path]:
    files: List[Path] = []
    for pat in _IMAGE_PATTERNS:
        files.extend(directory.glob(pat))
    return sorted(set(files), key=lambda p: p.name.lower())


def _is_merged_csv(path: Path) -> bool:
    name = path.name.lower()
    return any(marker in name for marker in _MERGED_CSV_MARKERS)


def find_first_grader_mnv_csvs(
    scan_root: Path,
    *,
    exclude_paths: Optional[Sequence[Path]] = None,
) -> List[Path]:
    """
    Locate the first grader's MNV CSV file(s) near the export bundle.

    Searches the export parent folder (where auto CSV export writes) and one
    level of subfolders, excluding second-reader output folders and any merged
    output CSVs. Newest first.
    """
    scan_root = Path(scan_root)
    excluded = {Path(p).resolve() for p in (exclude_paths or [])}

    search_dirs: List[Path] = [scan_root]
    try:
        for child in scan_root.iterdir():
            if child.is_dir() and not _is_workflow_output_dir(child):
                if child.name != "export":
                    search_dirs.append(child)
    except OSError:
        pass

    found: List[Path] = []
    for d in search_dirs:
        try:
            for csv_path in d.glob("MNV_*.csv"):
                rp = csv_path.resolve()
                if rp in excluded or _is_merged_csv(csv_path):
                    continue
                if any(
                    part.startswith(_WORKFLOW_OUTPUT_PREFIXES) for part in rp.parts
                ):
                    continue
                found.append(rp)
        except OSError:
            continue

    unique = sorted(set(found), key=lambda p: p.stat().st_mtime, reverse=True)
    return unique


def resolve_second_reader_scan(selected_path: Path) -> SecondReaderScan:
    """
    Normalize the second reader's folder selection to the export bundle and
    collect the exported en-face images plus the first grader's CSVs.

    Raises ValueError when no export bundle / images can be found.
    """
    selected = Path(selected_path).expanduser()
    if selected.is_file():
        selected = selected.parent
    if not selected.is_dir():
        raise ValueError(f"フォルダが見つかりません: {selected}")
    selected = selected.resolve()

    export_dir: Optional[Path] = None
    seen = set()
    for cand in _candidate_export_dirs(selected):
        try:
            rc = cand.resolve()
        except OSError:
            continue
        if rc in seen:
            continue
        seen.add(rc)
        if _dir_is_export_bundle(rc):
            export_dir = rc
            break

    warnings: List[str] = []

    if export_dir is None:
        # Fallback: the selected folder itself may directly hold graded images
        # (no meta/ bundle). Accept it only if it actually contains images.
        direct_images = _glob_images(selected)
        if not direct_images:
            raise ValueError(
                "メタデータフォルダ（export/images|masks|meta）が見つかりません。"
                "第1グレーダーの出力フォルダ（export の親フォルダ）を選択してください。"
            )
        warnings.append(
            "export/meta 構造が見つからないため、選択フォルダ内の画像を直接使用します。"
        )
        return SecondReaderScan(
            selected=selected,
            export_dir=selected,
            scan_root=selected,
            images_dir=selected,
            images=direct_images,
            meta_files=[],
            first_grader_csvs=find_first_grader_mnv_csvs(selected),
            warnings=warnings,
        )

    scan_root = export_dir.parent

    images_root = export_dir / "images"
    all_images: List[Path] = []
    for pat in _IMAGE_PATTERNS:
        all_images.extend(images_root.rglob(pat))
    all_images = sorted(set(all_images), key=lambda p: p.name.lower())
    if not all_images:
        raise ValueError(f"エキスポート画像が見つかりません: {images_root}")

    # Queue images from a single directory (institution subfolder). If more
    # than one institution folder exists, use the one with the most images.
    by_parent: dict = {}
    for img in all_images:
        by_parent.setdefault(img.parent, []).append(img)
    images_dir = max(by_parent, key=lambda d: len(by_parent[d]))
    if len(by_parent) > 1:
        skipped = sorted(d.name for d in by_parent if d != images_dir)
        warnings.append(
            f"複数の施設フォルダが見つかりました。{images_dir.name} を使用します"
            f"（未使用: {', '.join(skipped)}）。"
        )
    images = sorted(by_parent[images_dir], key=lambda p: p.name.lower())

    meta_files = sorted((export_dir / "meta").rglob("*.json"))
    if len(meta_files) != len(images):
        warnings.append(
            f"メタデータ件数 ({len(meta_files)}) と画像件数 ({len(images)}) が一致しません。"
        )

    return SecondReaderScan(
        selected=selected,
        export_dir=export_dir,
        scan_root=scan_root,
        images_dir=images_dir,
        images=images,
        meta_files=meta_files,
        first_grader_csvs=find_first_grader_mnv_csvs(scan_root),
        warnings=warnings,
    )


def _meta_fov_mm(meta: Dict[str, Any]) -> Optional[float]:
    for key in ("fov_mm", "scale_mm", "fov"):
        raw = meta.get(key)
        if raw is None or raw == "":
            continue
        try:
            v = float(raw)
        except (TypeError, ValueError):
            continue
        if v > 0:
            return v
    stratum = str(meta.get("stratum") or "").strip().lower()
    if stratum in {"small_3mm", "3mm", "3x3"}:
        return 3.0
    if stratum in {"small", "large", "6mm", "6x6"}:
        return 6.0
    return None


def load_meta_fov_by_stem(meta_files: Sequence[Path]) -> Dict[str, float]:
    """Map meta stem / lesion_id → fov_mm from export/meta JSON files."""
    out: Dict[str, float] = {}
    for path in meta_files:
        try:
            meta = json.loads(Path(path).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError, TypeError, ValueError):
            continue
        if not isinstance(meta, dict):
            continue
        fov = _meta_fov_mm(meta)
        if fov is None:
            continue
        stems = {
            Path(path).stem,
            str(meta.get("lesion_id") or "").strip(),
        }
        for stem in stems:
            if stem:
                out[stem] = float(fov)
    return out


def resolve_image_fov_map(
    images: Sequence[Path],
    meta_files: Sequence[Path],
) -> Tuple[Dict[str, float], Optional[float], List[str]]:
    """
    Build absolute-image-path → fov_mm from paired export/meta JSON.

    Returns ``(path_to_fov, default_fov, warnings)``. ``default_fov`` is the
    majority FOV among matched images (or None when nothing can be resolved).
    """
    warnings: List[str] = []
    by_stem = load_meta_fov_by_stem(meta_files)
    path_to_fov: Dict[str, float] = {}
    for img in images:
        fov = by_stem.get(img.stem)
        if fov is None:
            continue
        try:
            path_to_fov[str(Path(img).resolve())] = float(fov)
        except OSError:
            path_to_fov[str(img)] = float(fov)

    if not path_to_fov:
        if meta_files:
            warnings.append(
                "export/meta に有効な fov_mm / stratum が無く、解析スケールを自動設定できません。"
            )
        return {}, None, warnings

    counts = Counter(round(v, 6) for v in path_to_fov.values())
    default_fov = float(counts.most_common(1)[0][0])
    unmatched = len(images) - len(path_to_fov)
    if unmatched > 0:
        warnings.append(
            f"FOV メタ未対応の画像が {unmatched} 件あります（ダッシュボード既定スケールを使用）。"
        )
    if len(counts) > 1:
        warnings.append(
            f"メタの FOV が混在しています（多数派 {default_fov:g} mm を既定にします）。"
            " 画像ごとにセッション scale を切替えます。"
        )
    return path_to_fov, default_fov, warnings


def format_scale_dropdown_value(fov_mm: float) -> str:
    """Match dashboard Image Scale options (``1.0`` … ``12.0``)."""
    rounded = float(round(float(fov_mm)))
    if abs(float(fov_mm) - rounded) < 0.05 and 1 <= int(rounded) <= 12:
        return str(rounded)
    return f"{float(fov_mm):g}"


def second_reader_output_dir(scan_root: Path) -> Path:
    """
    Output folder for the second reader's own CSV.

    Created as a SIBLING of the first grader's output folder (scan_root), e.g.::

        parent/
        ├── output_folder_2026_08_08/        ← first grader (scan_root)
        └── second_reader_output_2026_08_08/ ← this folder
    """
    stamp = datetime.now().strftime("%Y_%m_%d")
    return Path(scan_root).resolve().parent / f"{_SECOND_READER_DIR_PREFIX}_{stamp}"


def integrated_output_dir(scan_root: Path) -> Path:
    """
    Output folder for the merged (統合解析データ) results — a sibling of both the
    first grader's and the second reader's output folders.
    """
    stamp = datetime.now().strftime("%Y_%m_%d")
    return Path(scan_root).resolve().parent / f"{_INTEGRATED_DIR_PREFIX}_{stamp}"
